### ISSUE TITLE
[Bug] drop all只丢出一个物品而不是全丢

### ISSUE THREAD

**Issue by xuanlv797** [Gu-ZT/Curtain#104]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

1.2.2

### Describe the bug - 问题描述

假人drop all只丢出一个物品而不是全丢

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Gu-ZT** [comment]
drop all 是背包里面全部物品都丢一个出来
dropStack all 才是丢出背包内所有物品
