### ISSUE TITLE
[Bug] mc1.16.5版本无法启动

### ISSUE THREAD

**Issue by IOPlimited** [Gu-ZT/Curtain#107]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

curtain-mc1.16.5-1.2.2+build.180

### Describe the bug - 问题描述

配置：jre1.8,mc1.16.5,forge36.2.34
只加装该mod时进入mod加载状态后直接崩溃
[崩溃报告](https://pan.baidu.com/s/1vZTMtGIdirDGSr8iDmFoJA?pwd=6lm6)

### To Reproduce - 复现问题

在制作整合包时加入该mod后崩溃
新下客户端只加入curtain依然崩溃

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Gu-ZT** [comment]
因为是Java17编译的
