### ISSUE TITLE
[Bug] 用Arclight服务端末影龙崩溃

### ISSUE THREAD

**Issue by Dr-WeiAL** [Gu-ZT/Curtain#109]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

1.2.2

### Describe the bug - 问题描述

Minecraft版本：1.19.2
错误报告：https://pastebin.com/mzcE4eQW
运行日志：https://pastebin.com/rpLx7E8P

在使用Arclight服务端进入末地时一切正常，在末影龙刷新出来的时候服务器崩溃

### To Reproduce - 复现问题

进入末地
刷新末影龙

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Gu-ZT** [comment]
请提供Minecraft版本、错误报告和运行日志

**Comment by Dr-WeiAL** [comment]
哦抱歉忘记加了(
同时附上那边的
https://github.com/IzzelAliz/Arclight/issues/1023

**Comment by Dr-WeiAL** [comment]
忘记放崩溃报告了，已补

**Comment by Gu-ZT** [comment]
与 #76 重复
已在 Arclight 1.0.3版本修复
