### ISSUE TITLE
【BUG】召唤假人不能锁定实体（如打怪，打盔甲架等），只能锁定方块

### ISSUE THREAD

**Issue by 1528218152** [Gu-ZT/Curtain#136]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

mc版本1.18.2 mod版本1.3.1 forge版本40.2.9

### Describe the bug - 问题描述

召唤假人不能锁定实体（如打怪，打盔甲架等），只能锁定方块
具体情况为刷怪塔收集部分使用假人挂机时，不管是直接挂假人用横扫3的剑，还是假人瞄准盔甲架，都无法打到怪物或盔甲架（无法触发横扫），确定假人能打到怪物或者盔甲架身后的方块。

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Gu-ZT** [comment]
此问题与 #100 所描述的问题一致
