### ISSUE TITLE
[Bug] 没有任何配置文件保存设置？

### ISSUE THREAD

**Issue by ghost** [Gu-ZT/Curtain#145]
### OS Version - 操作系统

Linux

### Version Details - 版本信息

1.3.2

### Describe the bug - 问题描述

无论是服务端玩还是单机玩，保存世界重新读档or重启服务器，所有设置的RULES就又需要重新设置。
我本以为这个Mod会像其他Mod一样创建一个配置文件在`config`文件夹下，但是并没有。本来就是这么设计的吗？

### To Reproduce - 复现问题

我新建了一个1.18.2+Forge 40.2.0的单窗帘Mod实例复现，log如下。
https://mclo.gs/Bm152ui

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Gu-ZT** [comment]
配置文件保存在存档目录下的`curtain.json`，此设计是为了让各个存档的设置分离
