### ISSUE TITLE
[Bug] 在服务器中使用curtain放置假人后占用内存不断升高直到崩溃

### ISSUE THREAD

**Issue by applenana** [Gu-ZT/Curtain#147]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

curtain : 1.2.2
mc : 1.19.2

### Describe the bug - 问题描述

在服务器中放置假人一段时间之后占用内存会不断升高
![UR~H0XUPMJW%KP ~Y5@IMM](https://github.com/Gu-ZT/Curtain/assets/83851967/dadabce6-2b72-44e9-ab86-05cfd814bc3d)
↑这是服务器即将崩溃时候的占用
再过一会mcser就崩溃

### To Reproduce - 复现问题

尝试使用Memory Leak Fix修复
可是无论是否使用Memory Leak Fix放置假人后，服务器仍然会占用升高直到崩溃

### This issue is unique - 这个issue是唯一的

- [x] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by applenana** [comment]
![RV$CNLE208})7Q_A) D40](https://github.com/Gu-ZT/Curtain/assets/83851967/0fd023c5-b6ed-49f0-8925-af8960c732ee)

**Comment by applenana** [comment]
> ![RV$CNLE208})7Q_A) D40](https://user-images.githubusercontent.com/83851967/284766322-0fd023c5-b6ed-49f0-8925-af8960c732ee.png)

补图

**Comment by xinghe0635** [comment]
问一下解决了吗

**Comment by applenana** [comment]
> 问一下解决了吗

没有，现在就是调大内存＋每晚重启服务器
