### ISSUE TITLE
[Bug] 进入存档时游戏卡住未响应

### ISSUE THREAD

**Issue by theabab2333** [Gu-ZT/Curtain#171]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

1.20.1-1.3.2

### Describe the bug - 问题描述

无法进入单机存档 游戏长时间未响应 不清楚到底是不是窗帘的问题 但是游戏最后的log显示窗帘error

### To Reproduce - 复现问题

启动游戏 进入存档 加载地图 未响应 https://mclo.gs/d03SGeS

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Gu-ZT** [comment]
![image](https://github.com/user-attachments/assets/54ddcc51-e115-4d35-a8f5-ea3f783f6d71)

**Comment by Gu-ZT** [comment]
![38cdac3ebf7fc95d3c4d0666530e5436_720](https://github.com/user-attachments/assets/818fa181-7f26-4d25-9f78-0c2bb52691e8)
