### ISSUE TITLE
[Bug] 和机械动力兼容性不好

### ISSUE THREAD

**Issue by hylnb** [Gu-ZT/Curtain#62]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

1.19.2 forge

### Describe the bug - 问题描述

          问题1：安装在服务器上，和机械动力，MEK模组(其他模组暂时没有测试过)兼容性不好，会导致机械动力0.5i版本传送带可以一节一节的拆除，mek管道不更新（此问题是一位朋友报告到MC百科上的，嗯四海皆为友，应该是单人情况下），虽然我自己的服务器也装了mek但是我还没开始玩这一部分，并不知道在服务器上是否有这个问题。
       问题2：还是在服务器上，会导致末地传送门传送时间明显变长（不确定是否是因为网络问题），不过末地传送门传送时间没变化。
        问题3：同样是一位MC百科的朋友指出的问题会导致机械动力模组火车轨道在某些情况下无法放置，但是会消耗轨道。
        问题4：会导致在服务器内经常断连。
        以上四个问题，均在卸载此模组后恢复正常。

### To Reproduce - 复现问题

          第一个问题复现，在地狱传送门附近，用机械动力模组切门，做刷怪塔，底下接了传送带，然后我就发现可以一节一节的拆传送带（应该也是更新问题），拆除传送带之后，上面的物品并不会掉到虚空去,额从这里应该可以看出我玩的是空岛，但是你可以在被拆除的传送带下面放东西甚至可以在缺失的那一节放，并不会影响传送带运行。第一次遇到这种话多了一点抱歉。
         MEK模组我只能把朋友的原话复制过来了，“会导致mek的管道无法更新”
        机械动力（create）轨道放置问题，“好像会导致机械动力的列车轨道在某些角度放不下来(会消耗轨道).把这个模组去掉之后就没有这个问题”
         地狱传送门传送时间明显变长（服务器内），这个只能说变长太多了所以一下就感觉出来了。
         问题四，这个因为我在造刷怪塔的时候传送了将近一分钟，还没回去，然后当我以为马上传送回去的时候我断连了，然后就是几次莫名奇妙的断联。
        卸载模组之后我用校园网玩都不会经常掉线。
        问题肯定是独一无二的，因为一个问题报告都没有。

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by hylnb** [comment]
嗯，我看另外两位兄台没有报告的意思，所以就一起报告过来了

**Comment by Gu-ZT** [comment]
请试试1.2.2是否仍旧存在此问题

**Comment by hylnb** [comment]
@Gu-ZT 关于昨天我提交的哪个无效错误，我还是想证明一下自己没有消遣你们。这个是我昨天录的视频，从pcl2上下载的真的用不了。我昨天提交的机械动力的bug可以删除，确定不是你们的问题，和你们说一声道歉。
链接：https://pan.baidu.com/s/14rB9GWpQFNGBqdgiaB7eFg?pwd=0000
提取码：0000
为什么上传不了大一点的视频
