### ISSUE TITLE
[Bug] 游戏崩溃

### ISSUE THREAD

**Issue by xuanlv797** [Gu-ZT/Curtain#75]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

1.2.1

### Describe the bug - 问题描述

加上模组就崩溃
[错误报告-2023-4-10_22.08.23.zip](https://github.com/Gu-ZT/Curtain/files/11190977/-2023-4-10_22.08.23.zip)

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Gu-ZT** [comment]
理论上已在1.2.2中修复，你刚好在修复后报告了此问题
