### ISSUE TITLE
[Bug] 进末地后服务器重启

### ISSUE THREAD

**Issue by Xu-i** [Gu-ZT/Curtain#76]
### OS Version - 操作系统

Linux

### Version Details - 版本信息

最新

### Describe the bug - 问题描述

[进末地后服务器重启[``
[crash-2023-04-11_19.24.30-server.txt](https://github.com/Gu-ZT/Curtain/files/11199833/crash-2023-04-11_19.24.30-server.txt)

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Forgot-Dream** [comment]
崩溃是与Arclight冲突引起的，我们将会在新的提交中修复此问题。同时我们也向arclight提交了相关issue [https://github.com/IzzelAliz/Arclight/issues/964](https://github.com/IzzelAliz/Arclight/issues/964)

**Comment by Forgot-Dream** [comment]
Arclight已经对此进行修复，请使用[Arclight-GreatHorn-1.0.3](https://github.com/IzzelAliz/Arclight/releases/tag/GreatHorn%2F1.0.3)版本进行测试，是否能复现此问题。
