### ISSUE TITLE
[Bug] 还是机械动力

### ISSUE THREAD

**Issue by hylnb** [Gu-ZT/Curtain#79]

**Comment by DancingSnow0517** [comment]
![image](https://user-images.githubusercontent.com/60736156/231643965-a69b36f6-36b7-4336-b236-54eabfba2ff7.png)
实际测试蓝图可用
包含mod `create-1.19.2-0.5.0.i.jar`, `curtain-mc1.19.2-1.2.2.jar`

**Comment by hylnb** [comment]
好吧！是机械动力和功能性存储不兼容。不包含末影抽屉的情况下蓝图正常，包含末影抽屉保存蓝图为空，抱歉，我马上就删除。
