### ISSUE TITLE
[Bug] 设置为默认后创建新世界不生效

### ISSUE THREAD

**Issue by Dr-WeiAL** [Gu-ZT/Curtain#97]
### OS Version - 操作系统

Windows

### Version Details - 版本信息

1.18.2-1.2.2

### Describe the bug - 问题描述

在一个世界里修改了一些规则并设置为默认后，
创建一个新的世界并不会生效这些已经设置为默认的规则。
这是我对默认的理解有错误还是说是什么原因呢？
如果是单个世界每次进入的默认，那么有没有计划搞一个全局默认呢(

### To Reproduce - 复现问题

旧世界：修改规则并设置为默认
新世界：没有任何规则被修改

### This issue is unique - 这个issue是唯一的

- [X] I have searched the issue tracker and did not find an issue describing my bug. - 我已经搜索问题追踪器并且没有发现相同的 issue。

**Comment by Gu-ZT** [comment]
这边的默认是为每个存档设置的，没有被设置为默认的选项将在下次进入存档时重置，暂时没有添加全局默认的计划
